### ISSUE TITLE
pretty-formatter fails on "All tests pass"

### ISSUE THREAD

**Issue by amorriscode** [jasancheg/sails-eslint#1]
When there are failing tests, pretty-formatter is calling repeating with a number instead of a string.

This results in the following error:

`throw new TypeError(`Expected \`input\` to be a \`string\`, got \`${typeof str}\``);`

Here is the full stack trace:

```
TypeError: Expected `input` to be a `string`, got `number`
    at module.exports (/Users/MisterShred/website/website-website/node_modules/sails-eslint/node_modules/repeating/index.js:7:9)
    at /Users/MisterShred/website/website-website/node_modules/sails-eslint/pretty-formatter.js:95:17
    at Array.map (native)
    at module.exports (/Users/MisterShred/website/website-website/node_modules/sails-eslint/pretty-formatter.js:84:21)
    at runLint (/Users/MisterShred/website/website-website/node_modules/sails-eslint/index.js:28:7)
    at /Users/MisterShred/website/website-website/node_modules/sails-eslint/index.js:52:7
    at Array.forEach (native)
    at processingQueue (/Users/MisterShred/website/website-website/node_modules/sails-eslint/index.js:46:8)
    at Hook.initialize (/Users/MisterShred/website/website-website/node_modules/sails-eslint/index.js:140:9)
    at Hook.bound [as initialize] (/Users/MisterShred/website/website-website/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/MisterShred/website/website-website/node_modules/sails/lib/hooks/index.js:74:14
    at /Users/MisterShred/website/website-website/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /Users/MisterShred/website/website-website/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/Users/MisterShred/website/website-website/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Users/MisterShred/website/website-website/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by fortil** [comment]
An answer? I have the same error

**Comment by amorriscode** [comment]
@fortil I went ahead and used `sails-hook-lint` instead.

**Comment by jasancheg** [comment]
A little late i know :(, but, the error has been solved!, Some plugins were outdated.

I really feel the delay, I had a lot of work and I have not paid enough attention to this repository, the fact is that I made the hook in a moment that I needed it for one of my projects, please excuse. I will be more careful about maintenance.
