### ISSUE TITLE
Failed to lift app: TypeError: Cannot read property 'debounce' of undefined

### ISSUE THREAD

**Issue by Wisperus** [jasancheg/sails-eslint#5]
> error: Failed to lift app: TypeError: Cannot read property 'debounce' of undefined
    at Hook.initialize (app\node_modules\sails-eslint\index.js:140:38)
    at Hook.wrapper [as initialize] (app\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at app\node_modules\sails\lib\hooks\index.js:107:18
    at app\node_modules\sails\node_modules\async\dist\async.js:421:16
    at processQueue (app\node_modules\sails\node_modules\async\dist\async.js:1565:20)
    at taskComplete (app\node_modules\sails\node_modules\async\dist\async.js:1588:9)
    at app\node_modules\sails\node_modules\async\dist\async.js:1612:17
    at app\node_modules\sails\node_modules\async\dist\async.js:906:16
    at Hook.loadModules (app\node_modules\sails\lib\hooks\index.js:157:14)
    at Hook.wrapper [as loadModules] (app\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at modules (app\node_modules\sails\lib\hooks\index.js:84:25)
    at runTask (app\node_modules\sails\node_modules\async\dist\async.js:1621:13)
    at app\node_modules\sails\node_modules\async\dist\async.js:1559:13
    at processQueue (app\node_modules\sails\node_modules\async\dist\async.js:1569:13)
    at Object.auto (app\node_modules\sails\node_modules\async\dist\async.js:1555:5)
    at Hook.load (app\node_modules\sails\lib\hooks\index.js:78:13)
    at Hook.wrapper [as load] (app\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at loadHook (app\node_modules\sails\lib\app\private\loadHooks.js:212:17)
    at app\node_modules\sails\lib\app\private\loadHooks.js:344:13
    at app\node_modules\sails\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (app\node_modules\sails\node_modules\async\dist\async.js:1003:9)
    at eachOf (app\node_modules\sails\node_modules\async\dist\async.js:1051:5)

**Comment by Paskalouis** [comment]
Hi,

Same here, I hope author checks this out.
